[id="running-automation-mesh-jobs"]
= Running automation mesh jobs

Automation mesh is a scalable cluster of Receptor nodes that execute Ansible playbooks.
{sdk-name} lets you invoke jobs directly on nodes in the automation mesh.

== Prerequisites

* Install {sdk-name} and requirements, including Ansible and Ansible Runner.
* Install link:https://github.com/ansible/receptor[Receptor].
* Install link:https://receptor.readthedocs.io/en/latest/index.html#installation[Receptorctl].

== Setting up a local automation mesh

Create a locally running cluster of Receptor nodes with configuration files in the `examples/receptor_config` directory:

[arabic]
. Open your `/etc/hosts` file for editing.
. Add the following entries to your `hosts` file:
+
[source,default,sub="attributes"]
----
127.0.0.1 foo.example.com
127.0.0.1 bar.example.com
127.0.0.1 baz.example.com
----

. Open a terminal and start the first Receptor node.
.. Activate your virtual environment for {sdk-name}.
+
[source,bash,sub="attributes"]
----
$ source env/bin/activate
----

.. Start a node with the `foo.yml` configuration.
+
[source,bash,sub="attributes"]
----
$ receptor --config foo.yml
----

. Open a new terminal and start the second Receptor node.
.. Activate your virtual environment for {sdk-name}.
.. Start a node with the `bar.yml` configuration.
+
[source,bash,sub="attributes"]
----
$ receptor --config bar.yml
----

. Open a new terminal and start the third Receptor node.
.. Activate your virtual environment for {sdk-name}.
.. Start a node with the `baz.yml` configuration.
+
[source,bash,sub="attributes"]
----
$ receptor --config baz.yml
----

. Verify that the automation mesh is running.
+
[source,bash,sub="attributes"]
----
$ receptorctl --socket /tmp/bar.sock status
----

== Invoking automation mesh jobs

Use {sdk-name} to run a playbook on automation mesh as follows:

[arabic]
. Open a terminal and change to the `examples` directory.
. Run the following command:
+
[source,bash,sub="attributes"]
----
$ python example_mesh_job.py
----

The `example_mesh_job.py` program has a main method that connects to the Receptor nodes and runs the `examples/datadir/project/pb.yml` playbook.
You can verify the job is successful when {sdk-name} prints the following to stdout:

[source,bash,sub="attributes"]
----
submitting work
work submitted
payload builder completed ok
getting results
got results
waiting for jobs
job done: True, has <x> events
----

== Troubleshooting

If you encounter issues with this scenario, troubleshoot as follows:

* Check your {sdk-name} installation. See xref:install-ansible-sdk[Installing {sdk-name}].
* Ensure you installed Ansible and Ansible Runner.
* Ensure Receptor is installed correctly.
* Ensure `receptorctl` is installed correctly.
* Ensure your `/etc/hosts` file contains entries for each local Receptor node.
* Ensure you run each Receptor node in a separate terminal in the {sdk-name} virtual environment.
